controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

mailslurp:
    path: /send-mail
    controller: App\Controller\MailSlurpController::sendEmail
    methods:    POST
