controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

mailslurp:
    path: /send_mail
    controller: App\Controller\MailslurpController::newEmail
    methods:    POST
